HR_System/Models/Holiday.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HR_System.Models
{
    public class Holiday
    {
        private string employeeName;
        private DateTime startDate;
        private DateTime endDate;
        private string cause;

        //public int EmployeeId { get => employeeId; set => employeeId = value; }
        public DateTime StartDate { get => startDate; set => startDate = value; }
        public DateTime EndDate { get => endDate; set => endDate = value; }
        public string Cause { get => cause; set => cause = value; }
        public string EmployeeName { get => employeeName; set => employeeName = value; }
    }
}

HR_System/Controllers/HrAdminController.cs
using HR_System.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HR_System.Controllers
{
    public class HrAdminController : Controller
    {
        // GET: HrAdmin
        HrAdmin hr = new HrAdmin();
        Utiles u = new Utiles();
        public ActionResult viewTrainingsList()
        {
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            var trainings = new List<Training>();
            try
            {
                trainings = hr.viewListOfTraining();
            }
            catch(Exception e)
            {

            }
            return View(trainings);
        }
        public ActionResult addTraining()
        {
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            ViewBag.skills = u.skill_list();
            ViewBag.positions = u.position_list();
            ViewBag.departments = u.department_list();
            return View();
        }

        [HttpPost]
        public ActionResult addTraining(FormCollection fc)
        {
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            try
            {
                
                Training training = new Training();
                training.TrainingName = fc["name"];
                training.StartDate = Convert.ToDateTime(fc["start_date"]);
                training.EndDate = Convert.ToDateTime(fc["end_date"]);
                training.Location = fc["location"];
                training.HoursPerDay =Convert.ToInt32(fc["hours_per_day"]);
                training.SkillId = Convert.ToInt32(fc["SkillId"]);
                training.MaxRank = Convert.ToInt32(fc["maxRank"]);
                training.PositionId = Convert.ToInt32(fc["PositionId"]);
                training.DepartmentId = Convert.ToInt32(fc["DepartmentId"]);
                training.MaxNumOfParticipants = Convert.ToInt32(fc["maxNumPart"]);
                int training_id = hr.insertTraining(training);

                TempData["msg"] = "A New Training Has Been Added Successfully !";
            }
            catch
            {

                TempData["msg"] = "An error has been occured ,please try again !";
            }

            return RedirectToAction("addTraining");
        }

       
        public ActionResult attendance_progress (FormCollection fc)
        {
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;

            string category = fc["Category"];
            string category_value = fc["category_value"];
            ViewBag.category_value = category_value;
            DateTime from = Convert.ToDateTime(fc["from"]);
            DateTime to = Convert.ToDateTime(fc["to"]);
            DataTable dt = hr.viewAttendanceReportProgress(category, category_value, from, to);
            List<DataPoint> points = new List<DataPoint>();

            for (var i = 0; i < dt.Rows.Count; i++)
            {

                string name = Convert.ToString(dt.Rows[i]["month"]);
                name += "/";
                name+= Convert.ToString(dt.Rows[i]["year"]); 
                double value = Convert.ToDouble(dt.Rows[i]["attendance_percentage"]);
                points.Add(new DataPoint(name, value));
            }
            ViewBag.Data = JsonConvert.SerializeObject(points);

            return View(dt);
        }

        public ActionResult attendance_comparison(FormCollection fc)
        {
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            string category = fc["Category"];
           
            DateTime date = Convert.ToDateTime(fc["date"]);
            
            DataTable dt = hr.viewAttendanceReportComparison(category,date);
            
            List<DataPoint> points = new List<DataPoint>();
            
            for (var i = 0; i < dt.Rows.Count; i++)
            {
                
               string name =Convert.ToString(dt.Rows[i]["category_name"]);
               double value = Convert.ToDouble(dt.Rows[i]["attendance_percentage"]);
                points.Add(new DataPoint(name,value));
            }
            ViewBag.Data = JsonConvert.SerializeObject(points);
            
            return View(dt);
        }

        public ActionResult performance_progress(FormCollection fc)
        {
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            string category = fc["Category"];
            string category_value = fc["category_value"];
            ViewBag.category_value = category_value;
            DateTime from = Convert.ToDateTime(fc["from"]);
            DateTime to = Convert.ToDateTime(fc["to"]);
            DataTable dt = hr.viewPerformanceReportProgress(category, category_value, from, to);
            List<DataPoint> points = new List<DataPoint>();

            for (var i = 0; i < dt.Rows.Count; i++)
            {

                string name = Convert.ToString(dt.Rows[i]["month"]);
                name += "/";
                name += Convert.ToString(dt.Rows[i]["year"]);
                double value = Convert.ToDouble(dt.Rows[i]["performance_percentage"]);
                points.Add(new DataPoint(name, value));
            }
            ViewBag.Data = JsonConvert.SerializeObject(points);

            return View(dt);
        }

        public ActionResult performance_comparison(FormCollection fc)
        {
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            string category = fc["Category"];

            DateTime date = Convert.ToDateTime(fc["date"]);

            DataTable dt = hr.viewPerformanceReportComparison(category, date);
            List<DataPoint> points = new List<DataPoint>();

            for (var i = 0; i < dt.Rows.Count; i++)
            {

                string name = Convert.ToString(dt.Rows[i]["category_name"]);
                double value = Convert.ToDouble(dt.Rows[i]["performance_percentage"]);
                points.Add(new DataPoint(name, value));
            }
            ViewBag.Data = JsonConvert.SerializeObject(points);

            return View(dt);
        }

        public ActionResult viewTraining(int training_id )
        {
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            Training training = hr.viewTraining(training_id);
            ViewBag.Training = training;
            ViewBag.skill_name = u.skill_name(training.SkillId);
            if(training.DepartmentId > 0)
            {
                ViewBag.Department_name = u.department_name(training.DepartmentId);
            }
            if(training.PositionId > 0)
            {
                ViewBag.Position_name = u.position_info(training.PositionId).PositionName;
            }
            DataTable dt = hr.employeeEnrolledInTraining(training_id);
            List<User_Info> recommendedEmployees = u.GetEmployeesInfo(hr.viewEmployeesForTraining(training_id));
            ViewBag.recommendedEmployees = recommendedEmployees;
            return View(dt);
        }
        public JsonResult assignTrainingToEmloyee(int trainingId, int employeeId)
        {
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            int value = hr.assignTrainingToEmloyee(trainingId, employeeId);
            return Json(value);
        }
            public void unassignEmployeeFromTraining(int training_id,int employee_id)
        {
            hr.unAssignEmployeeFromTraining(training_id, employee_id);

            
        }
        public JsonResult addEmployeeToTrainingByName(string userName,int trainingId)
        {
            int value = -1;

            try
            {
                value = hr.addEmployeeToTrainingByName(userName, trainingId);
                return Json(value);
            }
            catch(Exception e)
            {
                
            }
            return Json(value);
        }

        public ActionResult setBounaceCriteria()
        {
            DataTable dt = new DataTable();
            ViewBag.departments = u.department_list();
            ViewBag.positions = u.position_list();
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            return View();
        }
        [HttpPost]
        public ActionResult setBounaceCriteria(FormCollection fc)
        {

            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            ViewBag.departments = u.department_list();
            ViewBag.positions = u.position_list();
            Bonus bonus = new Bonus();
            bonus.DepartmentId =Convert.ToInt32(fc["DepartmentId"]);
            bonus.PositionId = Convert.ToInt32(fc["PositionId"]);
            bonus.MinSkillsRank = Convert.ToInt32(fc["quantity"]);
            bonus.MinPerformancePercentage = Convert.ToDouble(fc["performance"]);
            bonus.MinAttendancePercentage = Convert.ToDouble(fc["atten"]);
            bonus.BonusValue = Convert.ToDouble(fc["bonus"]);
            bonus.Description = Convert.ToString(fc["desc"]);
            DataTable dt = hr.setBounaceCriteria(bonus);
            return View(dt);
        }

        public ActionResult hireApplicant()
        {
            ViewBag.Applicants = u.applicants_list();
            ViewBag.Department = u.department_list();
            ViewBag.Position = u.position_list();
            var profile = this.Session["User"] as User_Info;
            ViewBag.LoggedUser = profile;
            return View();
        }
        [HttpPost]
        public ActionResult hireApplicant(FormCollection fc)
        {

HR_System/Views/HrAdmin/attendance_progress.cshtml
@using System.Data
@model DataTable

<!DOCTYPE html>
<html lang="en">
<head>

    <title>Attendance Progress</title>
    

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

        window.onload = function () {
         var position = '@ViewBag.LoggedUser.Position.PositionName';
            if (position != "Manager") {
                document.getElementById("strengthAndWeakness").style.visibility = "hidden";
                document.getElementById("promotion").style.visibility = "hidden";
                document.getElementById("companyPerformance").style.visibility = "hidden";
                document.getElementById("projectPerformance").style.visibility = "hidden";

            }
            if (position != "HR") {
                document.getElementById("trainingPage").style.visibility = "hidden";
                document.getElementById("attendanceReporting").style.visibility = "hidden";
                document.getElementById("performanceReporting").style.visibility = "hidden";
                document.getElementById("bonusCreteria").style.visibility = "hidden";
                document.getElementById("holidayAndPermission").style.visibility = "hidden";
                document.getElementById("hireApplicant").style.visibility = "hidden";

            }
            if (position != "TeamLeader") {
                document.getElementById("projectsAndTasks").style.visibility = "hidden";

            }
            var chart = new CanvasJS.Chart("chartContainer", {
	        animationEnabled: true,
	        theme: "light2", // "light1", "dark1", "dark2"
	        exportEnabled: true,
	        title: {
		        text: "Comparison graph"
                },
                dataPointWidth: 20,
	        data: [{
		        type: "column",
		        dataPoints:  @Html.Raw(ViewBag.Data)
	        }]
        });
        chart.render();

    }
    </script>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="~/css/colorpicker.css" />
    <link rel="stylesheet" href="~/css/datepicker.css" />
    <link rel="stylesheet" href="~/css/uniform.css" />
    <link rel="stylesheet" href="~/css/select2.css" />
    <link rel="stylesheet" href="~/css/matrix-style.css" />
    <link rel="stylesheet" href="~/css/matrix-media.css" />
    <link rel="stylesheet" href="~/css/bootstrap-wysihtml5.css" />
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
    <style type="text/css">
        #right {
            float: right;
        }
    </style>
</head>
<body>

    <!--Header-part-->
    <div id="header">
        <h1><a href="dashboard.html">Matrix Admin</a></h1>
    </div>
    <!--close-Header-part-->
    <!--top-Header-menu-->
    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav">
            <li class="dropdown" id="profile-messages">
                <a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Welcome User</span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><i class="icon-user"></i> My Profile</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-check"></i> My Tasks</a></li>
                    <li class="divider"></li>
                    <li><a href="login.html"><i class="icon-key"></i> Log Out</a></li>
                </ul>
            </li>
            <li class="dropdown" id="menu-messages">
                <a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a class="sAdd" title="" href="#"><i class="icon-plus"></i> new message</a></li>
                    <li class="divider"></li>
                    <li><a class="sInbox" title="" href="#"><i class="icon-envelope"></i> inbox</a></li>
                    <li class="divider"></li>
                    <li><a class="sOutbox" title="" href="#"><i class="icon-arrow-up"></i> outbox</a></li>
                    <li class="divider"></li>
                    <li><a class="sTrash" title="" href="#"><i class="icon-trash"></i> trash</a></li>
                </ul>
            </li>
            <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
            <li class=""><a title="" href="login.html"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
        </ul>
    </div>

    <!--start-top-serch-->
    <div id="search">
        <input type="text" placeholder="Search here..." />
        <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
    </div>
    <!--close-top-serch-->
    <!--sidebar-menu-->

    <div id="sidebar">
        <ul>
            <li class="submenu" id="trainingPage">
                <a href="#"><i class="icon icon-list"></i> <span>Training</span></a>
                <ul>
                    <li id="trainingBoard"><a href="@Url.Action("viewTrainingsList", "HrAdmin")">Training Board</a></li>
                    <li id="addTraining"><a href="@Url.Action("addTraining", "HrAdmin")">Add Training</a></li>
                </ul>
            </li>
            <li id="myAttendance"><a href="@Url.Action("viewAttendanceLog", "User")"><i class="icon icon-th"></i> <span>My Attendance</span></a></li>
            <li id="taskSceduale"><a href="@Url.Action("viewTasks", "Employee")"><i class="icon icon-th"></i> <span>Task Sceduale</span></a></li>
            <li id="feedback"><a href="@Url.Action("getFeedbackList", "Employee")"><i class="icon icon-th"></i> <span>Feedback</span></a></li>
            <li id="myAttendanceProgress"><a href="@Url.Action("showAttendanceProgress", "Employee")"><i class="icon icon-th"></i> <span>My Attendance Progress</span></a></li>
            <li id="myPerformanceProgress"><a href="@Url.Action("showPerformanceProgress", "Employee")"><i class="icon icon-th"></i> <span>My Performance Progress</span></a></li>

            <li class="submenu" id="attendanceReporting">
                <a href="#"><i class="icon icon-list"></i> <span>Attendance Reporting</span></a>
                <ul>
                    <li id="attendanceProgress" class="active"><a href="@Url.Action("attendance_progress", "HrAdmin")">Progress</a></li>
                    <li id="attendanceComparison"><a href="@Url.Action("attendance_comparison", "HrAdmin")">Comparison</a></li>
                </ul>
            </li>
            <li class="submenu" id="performanceReporting">
                <a href="#"><i class="icon icon-list"></i> <span>Performance Reporting</span></a>
                <ul>
                    <li id="performanceProgress"><a href="@Url.Action("performance_progress", "HrAdmin")">Progress</a></li>
                    <li id="performanceComparison"><a href="@Url.Action("performance_comparison", "HrAdmin")">Comparison</a></li>
                </ul>
            </li>
            <li class="submenu" id="projectsAndTasks">
                <a href="#"><i class="icon icon-list"></i> <span>Projects and Tasks</span></a>
                <ul>
                    <li id="projects"><a href="@Url.Action("projectsList", "TeamLeader")">Projects</a></li>
                    <li id="tasks"><a href="@Url.Action("getCurrentProject", "TeamLeader")">Tasks</a></li>
                </ul>
            </li>

            <li id="bonusCreteria"> <a href="@Url.Action("setBounaceCriteria", "HRAdmin")"><i class="icon icon-list"></i> <span>Bonus Creteria</span></a></li>
            <li id="promotion"> <a href="@Url.Action("getSuitableEmployeesForPromotion", "Manager")"><i class="icon icon-list"></i> <span>Promotion</span></a></li>
            <li id="strengthAndWeakness"> <a href="@Url.Action("weaknessAndStrength", "Manager")"><i class="icon icon-list"></i> <span>Strength And Weakness Fields</span></a></li>
            <li id="companyPerformance"> <a href="@Url.Action("companyPerformanceReport", "Manager")"><i class="icon icon-list"></i> <span>Company Performance</span></a></li>
            <li id="projectPerformance"> <a href="@Url.Action("projectPerformanceReport", "Manager")"><i class="icon icon-list"></i> <span>Project Performance</span></a></li>
            <li id="holidayAndPermission"> <a href="@Url.Action("holidays", "HrAdmin")"><i class="icon icon-list"></i> <span>Holidays and Permissions</span></a></li>
            <li id="hireApplicant"> <a href="@Url.Action("hireApplicant", "HrAdmin")"><i class="icon icon-list"></i> <span>Hire Applicant</span></a></li>

        </ul>
    </div>

    <div id="content">
        <div id="content-header">
            <div id="breadcrumb"> <a href="#" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="#" class="current">Attendance Progress</a> </div>
            <h1>Progress</h1>
        </div>
        <div class="container-fluid">
            <hr>
            <form method="post">
                @Html.DropDownList("Category", new List<SelectListItem>
      {
                   new SelectListItem{ Text="Employee", Value = "Employee" },
                   new SelectListItem{ Text="Department", Value = "Department" },
                   new SelectListItem{ Text="Position", Value = "Position" }

                }, "Select Category")
                </br>
                <input name="category_value" type="text" class="span3" placeholder="Search" />
                <div data-date="12-02-2012" class="input-append date datepicker">
                    <input name="from" type="text" placeholder="From" data-date-format="mm-dd-yyyy" class="span3">
                    <span class="add-on"><i class="icon-th"></i></span>
                </div>
                <div data-date="12-02-2012" class="input-append date datepicker">
                    <input name="to" type="text" placeholder="To" data-date-format="mm-dd-yyyy" class="span3">
                    <span class="add-on"><i class="icon-th"></i></span>
                </div>
                <div>
                    <button class="btn btn-primary">Set</button>
                </div>
            </form>
            <div class="row-fluid">
                <div class="span6">
                    <h5>@ViewBag.category_value</h5>
                    <div class="widget-content">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Month-Year</th>
                                    <th>Attendance Percentage</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (DataRow dr in Model.Rows)
                                {

                                    <tr>
                                        <td>@dr["month"]-@dr["year"]</td>
                                        <td>@dr["attendance_percentage"] %</td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <div id="chartContainer" style="height: 370px; width: 100%;"></div>

        </div>
    </div>
    <!--Footer-part-->
    <div class="row-fluid">
        <div id="footer" class="span12"> 2013 &copy; Matrix Admin. Brought to you by <a href="http://themedesigner.in">Themedesigner.in</a> </div>
    </div>
    <!--end-Footer-part-->
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery.ui.custom.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/bootstrap-colorpicker.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/jquery.toggle.buttons.js"></script>
    <script src="~/js/masked.js"></script>
    <script src="~/js/jquery.uniform.js"></script>
    <script src="~/js/select2.min.js"></script>
    <script src="~/js/matrix.js"></script>
    <script src="~/js/matrix.form_common.js"></script>
    <script src="~/js/wysihtml5-0.3.0.js"></script>
    <script src="~/js/jquery.peity.min.js"></script>
    <script src="~/js/bootstrap-wysihtml5.js"></script>
    <script>
        $('.textarea_editor').wysihtml5();
    </script>

</body>
</html>